name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env create --file environment.yml --name supermariopy
        $CONDA/bin/conda init bash
        $CONDA/bin/conda activate
        pip install pydensecrf
    - name: Test with pytest
      run: |
        $CONDA/bin/conda activate supermariopy
        chmod +x ./run_tests.sh
        ./run_tests.sh
